### ISSUE TITLE
Loading yml data - using yaml_db gem

### ISSUE THREAD

**Issue by wejrowski** [engineyard/ey-docs#82]
Hello, 

I am attempting to use the yaml_db gem to load data I exported locally. (btw if there's a better alternate to doing this let me know).

I successfully deploy and run my rake db:migrate. But I cannot run 

```
rake db:data:load
```

When I do I get this: 

```
rake aborted!
You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.each
/data/spreecart/shared/bundled_gems/ruby/1.9.1/gems/yaml_db-0.2.1/lib/serialization_helper.rb:85:in `load_records'
/data/spreecart/shared/bundled_gems/ruby/1.9.1/gems/yaml_db-0.2.1/lib/serialization_helper.rb:74:in `load_table'
/data/spreecart/shared/bundled_gems/ruby/1.9.1/gems/yaml_db-0.2.1/lib/yaml_db.rb:63:in `block (2 levels) in load_documents'
/data/spreecart/shared/bundled_gems/ruby/1.9.1/gems/yaml_db-0.2.1/lib/yaml_db.rb:61:in `each'
/data/spreecart/shared/bundled_gems/ruby/1.9.1/gems/yaml_db-0.2.1/lib/yaml_db.rb:61:in `block in load_documents'
/usr/lib/ruby/1.9.1/syck.rb:235:in `call'
/usr/lib/ruby/1.9.1/syck.rb:235:in `load_documents'
/usr/lib/ruby/1.9.1/syck.rb:235:in `load_documents'
/data/spreecart/shared/bundled_gems/ruby/1.9.1/gems/yaml_db-0.2.1/lib/yaml_db.rb:60:in `load_documents'
/data/spreecart/shared/bundled_gems/ruby/1.9.1/gems/yaml_db-0.2.1/lib/serialization_helper.rb:57:in `block in load'
/data/spreecart/shared/bundled_gems/ruby/1.9.1/gems/activerecord-3.0.9/lib/active_record/connection_adapters/abstract/database_statements.rb:139:in `transaction'
/data/spreecart/shared/bundled_gems/ruby/1.9.1/gems/yaml_db-0.2.1/lib/serialization_helper.rb:56:in `load'
/data/spreecart/shared/bundled_gems/ruby/1.9.1/gems/yaml_db-0.2.1/lib/serialization_helper.rb:31:in `load'
/data/spreecart/shared/bundled_gems/ruby/1.9.1/gems/yaml_db-0.2.1/lib/tasks/yaml_db_tasks.rake:35:in `block (3 levels) in <top (required)>'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:205:in `call'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:205:in `block in execute'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:112:in `invoke_task'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:90:in `block (2 levels) in top_level'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:90:in `each'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:90:in `block in top_level'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:62:in `block in run'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/usr/bin/rake:19:in `load'
/usr/bin/rake:19:in `<main>'
Tasks: TOP => db:data:load
```

**Comment by joshbhamilton** [comment]
You should open a ticket for the Support teams to look into. If you go to http://support.cloud.engineyard.com/, someone will be able to address the issues you're seeing.

**Comment by papayaah** [comment]
this doesn't only happen to engine yard - it happens ot my local dev environment too.
